baseURL = "http://efner.id/"
languageCode = "en-us"
title = "Efner.ID"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "Febriansyah NR"
author = "Efner.ID"
description = "Seterampil-terampilnya pencuri, tidak akan bisa mencuri pengetahuan seseorang. Oleh karena itu pengetahuan adalah harta terbaik dan teraman untuk diperoleh. ― L. Frank Baum, The Lost Princess of Oz"
profilePicture = "images/profile.jpeg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/febrianrasyiid/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/fbriansyah"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/fbriansyah/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:febrian@efner.id"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "post"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"